### PR TITLE
feat: [SEM-217] create buttons for user management section 

### PR DESCRIPTION
**Pull request by MirianColque**
#217
This is my storybook:

### CODE REVIEW

**Comment by MirianColque** [comment]
image

https://ditmar.github.io/backoffice-openscience/branch-SEM-217/?path=/story/ui-components-atoms-true-false-button--true

**Review by Ditmar — CHANGES_REQUESTED** [review]
agrega opciones para hacer boton responsivo en base al respon-to que esta publicando en globals.

**Comment by Ditmar** [comment]
image
Haz que el boton sea responsivo

**Comment by MirianColque** [comment]
image
css responsivo ya corregido
https://github.com/Ditmar/backoffice-openscience/pull/254

**Pull request closed without merging**
