### PR TITLE
feat:add colors[sem-031]

### PR DESCRIPTION
**Pull request by secm10**

### CODE REVIEW

**Review by Ditmar — APPROVED** [review]

**Review by Ditmar — CHANGES_REQUESTED** [review]
rebase your branch, check the conflicts files

**Comment by secm10** [comment]
engineer already rebase my branch

**Comment by DanX3N0** [comment]
check the repetition of some colors:
{9B2A484C-4B9E-4F31-90ED-902892D23F6F}

**Comment by secm10** [comment]
engineer modify the name of colors of different shades

**Review by Ditmar — APPROVED** [review]

**Pull request merged**
