### PR TITLE
SEM-90

### PR DESCRIPTION
**Pull request by cinthiaastoraiqueh**
Necesitamos implementar un componente que contenga los elementos que se muestran en la imagen, conteniendo así todos los campos del formulario, además de integrar el componente de edición que se muestra en la imagen.

### CODE REVIEW

**Comment by cinthiaastoraiqueh** [comment]
https://ditmar.github.io/backoffice-openscience/branch-SEM-62/?path=/story/ui-components-atoms-articleinput--article


https://ditmar.github.io/backoffice-openscience/branch-SEM-62/?path=/story/ui-components-atoms-dateinput--date

https://ditmar.github.io/backoffice-openscience/branch-SEM-62/?path=/story/ui-components-atoms-textinput--default

https://ditmar.github.io/backoffice-openscience/branch-SEM-62/?path=/story/ui-components-atoms-yearinput--year-input-story

https://ditmar.github.io/backoffice-openscience/branch-SEM-62/?path=/story/ui-components-molecules-volumemanagement--default

**Comment by DanX3N0** [comment]
check this: 
image

image

**Comment by Ditmar** [comment]
image
it is not controlling the inputs

**Review by Ditmar — CHANGES_REQUESTED** [review]
please check the values of the forms

**Comment by cinthiaastoraiqueh** [comment]
note:
add three variants 
normal 
error  red
success green

**Pull request closed without merging**
