### PR TITLE
feature/sem 97

### PR DESCRIPTION
**Pull request by nnina32**

### CODE REVIEW

**Comment by nnina32** [comment]
Please I want a review of my PR
https://ditmar.github.io/backoffice-openscience/branch-feature/SEM-97/?path=/story/ui-components-atoms-danger-button

**Comment by DanX3N0** [comment]
check the url:

**Comment by nnina32** [comment]
https://ditmar.github.io/backoffice-openscience/branch-feature/sem-97/?path=/story/ui-components-atoms-danger-button

**Review by Ditmar — CHANGES_REQUESTED** [review]
rebase the pr fix the conflicts and remove the chatgpt comments

**Comment by nnina32** [comment]
https://ditmar.github.io/backoffice-openscience/branch-sem-97/?path=/story/ui-components-atoms-danger-button--small
my storybook and new rebase

**Comment by nnina32** [comment]
Please I want a review of my PR:
https://ditmar.github.io/backoffice-openscience/branch-sem-97/?path=/story/ui-components-atoms-danger-button--small

**Comment by nnina32** [comment]
https://ditmar.github.io/backoffice-openscience/branch-sem-97/?path=/story/ui-components-atoms-danger-button

**Comment by nnina32** [comment]
http://localhost:6006/?path=/story/ui-components-atoms-danger-button--small

**Review by Ditmar — CHANGES_REQUESTED** [review]
please check the deleted files. probably it is an error in the rebase

**Pull request closed without merging**
